config/routes.rb
Rails.application.routes.draw do
  devise_for :revisers
  devise_for :admins
  devise_for :users,  path: 'users', controllers: {
    sessions: 'users/sessions'
  }
  root 'home#index'
  namespace :admin do
    resources :asistencias
    resources :propuestas
    resources :revisers
end
namespace :user do
resources :asistencias
resources :propuestas
end
namespace :reviser do
resources :propuestas
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reviser.rb
class Reviser < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :propuestum

end

app/controllers/admin/revisers_controller.rb
class Admin::RevisersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_revisers, only: [:show, :edit, :update, :destroy]

  # GET /asistencia
  # GET /asistencia.json
  def index
    @revisers = Reviser.all
  end

  # GET /asistencia/1
  # GET /asistencia/1.json
  def show
  end

  # GET /asistencia/new
  def new
    @asistencium = Asistencium.new
  end

  # GET /asistencia/1/edit
  def edit
    @asistencium = Asistencium.find params[:id]
  end

  # POST /asistencia
  # POST /asistencia.json
  def create
    @success=false
    @asistencium = Asistencium.new(asistencium_params)
      if @asistencium.valid?
      @asistencium.save
      @success=true
      redirect_to admin_asistencias_path, notice: "Asistencia creado exitosamente"
    else
      render :new
      end

  end

  # PATCH/PUT /asistencia/1
  # PATCH/PUT /asistencia/1.json
  def update
    @success=true
    if Asistencium.exists?(params[:id])
      @asistencium = Asistencium.find params[:id]
      if @asistencium.update(asistencium_params)

        redirect_to admin_asistencias_path, notice: "asistencium editado exitosamente"
      else
        flash.now[:alert] = "Ha ocurrido un error"
        render :edit
      end
    else
      redirect_to admin_asistencias_path, alert: "asistencium no existe"
    end
  end

  # DELETE /asistencia/1
  # DELETE /asistencia/1.json
  def destroy
    @asistencium.destroy
    respond_to do |format|
      format.html { redirect_to admin_asistencias_path, notice: 'Asistencium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asistencium
      @asistencium = Asistencium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asistencium_params
      params.require(:asistencium).permit(:id,:nombre, :apellido, :correo, :telefono, :institucion)
    end
end

app/controllers/reviser/propuestas_controller.rb
class Reviser::PropuestasController < ApplicationController
  before_action :authenticate_reviser!
  before_action :set_propuestum, only: [:show, :edit, :update, :destroy]
  # GET /propuesta
  # GET /propuesta.json
  def index
    @propuestas = Propuestum.where reviser_id: current_reviser.id
  end
  # GET /propuesta/1
  # GET /propuesta/1.json
  def show

  end

  # GET /propuesta/new
  def new
    @propuestum = Propuestum.new
  end

  # GET /propuesta/1/edit
  def edit
    @propuestum = Propuestum.find params[:id]
  end

  # POST /propuesta
  # POST /propuesta.json
  def create
    @success=false
    @propuestum = Propuestum.new(propuestum_params)
      if @propuestum.valid?
      @propuestum.save
      @success=true
      redirect_to reviser_propuestas_path, notice: "propuesta creado exitosamente"
    else

      end

  end

  # PATCH/PUT /propuesta/1
  # PATCH/PUT /propuesta/1.json
  def update
    @success=true
    if Propuestum.exists?(params[:id])
      @propuestum = Propuestum.find params[:id]
      if @propuestum.update(propuestum_params)

        redirect_to reviser_propuestas_path, notice: "propuestum editado exitosamente"
      else
        flash.now[:alert] = "Ha ocurrido un error"
        render :edit
      end
    else
      redirect_to reviser_propuestas_path, alert: "propuestum no existe"
    end
  end

  # DELETE /propuesta/1
  # DELETE /propuesta/1.json
  def destroy
    @propuestum.destroy
    respond_to do |format|
      format.html { redirect_to reviser_propuestas_path, notice: 'propuestum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_propuestum
      @propuestum = Propuestum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def propuestum_params
      params.require(:propuestum).permit(:nombre, :titulo, :correo, :organizacion, :resumen, :rating)
    end
end

app/controllers/revisers/confirmations_controller.rb
# frozen_string_literal: true

class Revisers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/revisers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Revisers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /revisers/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/revisers/passwords_controller.rb
# frozen_string_literal: true

class Revisers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/revisers/registrations_controller.rb
# frozen_string_literal: true

class Revisers::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_user, except: [:new, :create]

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute,:nombre,:telefono])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute,:nombre,:telefono])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/revisers/sessions_controller.rb
# frozen_string_literal: true

class Revisers::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/revisers/unlocks_controller.rb
# frozen_string_literal: true

class Revisers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/revisers/edit.html.erb
<div class="container">
  <%= content_for :page_title, "Editar la propuesta" %>
  <%= react_component('PropuestaFormAdmin',propuestaId:@propuestum[:id]) %>
</div>

app/views/admin/revisers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
  <div class="col-lg-12">
<div class="card">
  <div class="card-header">
   Lista de propuestas
 </div>
  <div class="card-body">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Nombre</th>
      <th>titulo</th>
      <th>Correo</th>
      <th>organizacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @propuestas.each do |propuestum| %>
      <tr>
        <td><%= propuestum.nombre %></td>
        <td><%= propuestum.titulo %></td>
        <td><%= propuestum.correo %></td>
        <td><%= propuestum.organizacion %></td>
        <td><%= link_to 'Editar datos', edit_admin_propuesta_path(propuestum), class:"btn btn-default btn-primary"   %></td>
        <td><%= link_to 'Ver', admin_propuesta_path(propuestum), class:"btn btn-default btn-primary"   %></td>
        <td><% propuestum.rating.to_i.times do  %>
         <span class="glyphicon glyphicon-star"></span>
        <% end %>
        <% propuestum.blank_stars.times do %>
        <span class="glyphicon glyphicon-star-empty"></span>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
  <div class="card-footer text-muted">
    <%= link_to 'Crear nueva propuesta', new_admin_propuesta_path , class:"btn btn-default btn-primary"%>
    <%= link_to 'Volver', root_path, class:"btn btn-default btn-primary" %>
  </div>
</div>
</div>
</div>
</div>
<br>

app/views/admin/revisers/new.html.erb
<%= react_component('PropuestaFormAdmin') %>

app/views/admin/revisers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>Datos de la propuesta</h1>
<div class="card">
  <div class="card-body">
        <div class="card-group">
        <div class="card">
          <div class="card-header">
            Datos
          </div>
          <div class="card-body">
    <p>
      <strong>Nombre:</strong>
      <%= @propuestum.nombre %>
    </p>

    <p>
      <strong>Titulo:</strong>
      <%= @propuestum.titulo %>
    </p>

    <p>
      <strong>Correo:</strong>
      <%= @propuestum.correo %>
    </p>

    <p>
      <strong>Organización:</strong>
      <%= @propuestum.organizacion %>
    </p>
</div>
</div>


    <div class="card">
      <div class="card-header">
        Resumen
      </div>
        <div class="card-body">
    <p>
      <%= @propuestum.resumen %>
    </p>
    </div>
  </div>
  </div>
  </div>

  <div class="card-footer text-muted">
    <%= link_to 'Editar datos', edit_admin_propuesta_path(@propuestum), class:"btn btn-default btn-primary" %>
    <%= link_to 'Volver', admin_propuestas_path, class:"btn btn-default btn-primary" %>

    </div>

</div>
</div>