config/routes.rb
Rails.application.routes.draw do
  devise_for :revisers
  devise_for :admins
  devise_for :users,  path: 'users', controllers: {
    sessions: 'users/sessions'
  }
  root 'home#index'
  namespace :admin do
    resources :asistencias
    resources :propuestas
    resources :revisers
end
namespace :user do
resources :asistencias
resources :propuestas
end
namespace :reviser do
resources :propuestas
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_carousel.html.erb
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
  <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
  <li data-target="#myCarousel" data-slide-to="1"></li>
  <li data-target="#myCarousel" data-slide-to="2"></li>
</ol>

  <div class="carousel-inner">
    <div class="carousel-item active">
        <%= image_tag("fondo.png", :alt => "rss feed", class:"tales") %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Slide 1</h3>
          <p>es la slide 1.</p>
        </div>
    </div>
    <div class="carousel-item">
      <%= image_tag("fondo.png", :alt => "rss feed", class:"tales") %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Slide 2</h3>
        <p>es la slide 2.</p>
      </div>
    </div>

    <div class="carousel-item">
    <%= image_tag("fondo.png", :alt => "rss feed", class:"tales") %>
    <div class="carousel-caption d-none d-md-block">
      <h3>Slide 3</h3>
      <p>es la slide 3.</p>
    </div>

      </div>
  </div>
  <a  class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer navbar-fixed-bottom">
  <div class="container">
    <p class="float-right"><a class="glyphicon glyphicon-hand-up" href="#"></a></p>

      <ul>
        <li> TDD Team</li>

      </ul>


  </div>


</footer>

app/views/layouts/_header.html.erb
<header>


<nav class="navbar navbar-expand-lg " style="background-color: #101522;">
  <%= link_to image_tag("image2vector.svg",width:"150", height:"30"), root_path, class: "navbar-brand",id:"boton-home" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="glyphicon glyphicon-menu-hamburger"></span>  </button>


  <div class="collapse navbar-collapse" id="navbarNavDropdown" >
    <ul class=" navbar-nav">
      <li class="menu-active" >
        <a id="boton-home" class="nav-link" href="/">Home</a></li>
      <% if admin_signed_in? %>
      <li class="nav-item"><%= link_to "Ver Asistencias", admin_asistencias_path,class:"nav-link"%></li>
      <li class="nav-item"><%= link_to "Ver Propuestas", admin_propuestas_path,class:"nav-link"%></li>
      <% end %>
      <% if user_signed_in? %>
      <li class="nav-item"><%= link_to "Ver mis Asistencias", user_asistencias_path,class:"nav-link"%></li>
      <li class="nav-item"><%= link_to "Ver mis Propuestas", user_propuestas_path,class:"nav-link"%></li>
      <% end %>
      <% if reviser_signed_in? %>
      <li class="nav-item"><%= link_to "Ver Propuestas", reviser_propuestas_path,class:"nav-link"%></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <ul class="">
          </ul>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if admin_signed_in? %>
          <li class="nav-item"><%= link_to "Salir", destroy_admin_session_path, method: :delete ,class:"nav-link"%></li>
          <% else %>
          <% if !user_signed_in? %>
          <% if !reviser_signed_in? %>
          <li class="nav-item" ><%= link_to "Ingresar General Chair", new_admin_session_path ,class:"nav-link" %></li>
          <% end %>
          <% end %>
          <% end %>

          <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "Salir", destroy_user_session_path, method: :delete,class:"nav-link" %></li>
          <% else %>
          <% if !admin_signed_in?  %>
            <% if !reviser_signed_in?  %>
          <li class="nav-item" ><%= link_to "Ingresar Usuario", new_user_session_path,class:"nav-link"  %></li>
          <% end %>
          <% end %>
        <% end %>

        <% if reviser_signed_in? %>
        <li class="nav-item"><%= link_to "Salir", destroy_reviser_session_path, method: :delete,class:"nav-link" %></li>
        <% else %>
        <% if !admin_signed_in? %>
          <% if !user_signed_in? %>
        <li class="nav-item"><%= link_to "Ingresar Revisador", new_reviser_session_path,class:"nav-link"  %></li>
        <% end %>
        <% end %>
      <% end %>
      </ul>
      </div><!--/.nav-collapse -->

</nav>





</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>ReactRails</title>






    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'hello_react' %>
     <%= javascript_pack_tag 'RegistroFormUser' %>
     <%= javascript_pack_tag 'RegistroFormAdmin' %>
     <%= javascript_pack_tag 'PropuestaFormAdmin' %>
     <%= javascript_pack_tag 'PropuestaFormUser' %>
     <%= javascript_pack_tag 'PropuestaFormReviser' %>
     <%= javascript_pack_tag 'AsignarRevisadorFormAdmin' %>
     <%= javascript_pack_tag 'AprobarFormAdmin' %>


     <%= csrf_meta_tags %>
     <%= csp_meta_tag %>
  </head>

<header>
    <%= render "layouts/header" %>
</header>

  <body>



<footer>
      <%= render "layouts/footer" %>
</footer>
    <%= yield %>

  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>












</html>